### ISSUE TITLE
MAPA MENTAL DE LA COMUNICACION ORAL Y ESCRITA

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-4-mapa-mental-irvinjs22620075#1]
![COMUNICACIÓN ORAL Y ESCRIT4](https://user-images.githubusercontent.com/112287287/191159149-36417591-8171-48f6-867b-cb85ff5bb138.png)

**Comment by 11042002** [comment]
Tu calificación es de: 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
